# Application Base Configuration
spring.application.name=PaySim
spring.profiles.active=dev

# Server
server.port=8080
server.error.include-message=always
server.error.include-stacktrace=never


# Actuator & Observability
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.redis.enabled=false
management.metrics.tags.application=${spring.application.name}

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [reqId=%X{requestId}] - %msg%n
logging.level.com.Project.UPI_Simulation=INFO
logging.level.org.springframework.security=INFO

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.show-actuator=true
